shared: &shared
  url_cobrand_session_token: "/authenticate/coblogin"
  url_get_all_content_services: "/jsonsdk/ContentServiceTraversal/getAllContentServices"

development:
  <<: *shared
  url_base: "https://rest.developer.yodlee.com/services/srest/restserver/v1.0"
  username: "sbCobNate Synaptian"
  password: "118414a5-9525-4ad1-bce1-d5438ec30ec3"
  register_users: "false"

test:
  <<: *shared
  url_base: "https://rest.developer.yodlee.com/services/srest/restserver/v1.0"
  username: "sbCobNate Synaptian"
  password: "118414a5-9525-4ad1-bce1-d5438ec30ec3"
  register_users: "false"

production:
  <<: *shared
  url_base:
  username:
  password:
  register_users: "true"
